### ISSUE TITLE
Document Enhanced : How to deploy tcp/udp server with istio+kubernetes?

### ISSUE THREAD

**Issue by netroby** [istio/old_issues_repo#14]
Document Enhanced : How to deploy tcp/udp server with istio+kubernetes?

Such as deploy an tcp (echo) server , deploy an dns server ?

need some advance document guide us. please improve it.

**Comment by kyessenov** [comment]
The protocol name in the Kubernetes service definition defines the application protocol (see https://istio.io/docs/tasks/integrating-services-into-istio.html#injecting-envoy-sidecar-into-a-deployment). However, there are major limitations with TCP/UDP across Istio:
1. UDP is not supported by Envoy at all;
2. TCP is not supported by Mixer and is supported by Envoy for the basic (k8s-baseline) routing only.

Both issues should be solved in the near future.

**Comment by netroby** [comment]
Look's the istio not ready for real production use. TCP/UDP was very common protocol, which should be support.

**Comment by kyessenov** [comment]
Are you utilizing TCP sockets directly or using some higher-level TCP-based protocol? Envoy understands several application protocols (redis among them) that can provide more valuable metadata about the traffic.

**Comment by zvikaga** [comment]
The "redis" support has cough my eyes. Would like to know where and how should I define this in the service manifest.
Second, does this config will add mixer parameters to this tcp filter in the envoy's config file?

Thanks

**Comment by linsun** [comment]
https://github.com/istio/istio/issues/766 will help with the tcp piece of this.

**Comment by louiscryan** [comment]
This bug is pretty stale and has likely been superceded. We have pretty extensive TCP support

**Comment by ldemailly** [comment]
UDP support is tracked here: https://github.com/istio/istio/issues/1430
