### ISSUE TITLE
Provide an easy way to trace which envoy version is being used in the proxy_debug and release docker images

### ISSUE THREAD

**Issue by mdhume** [istio/old_issues_repo#176]
**Is this a BUG or FEATURE REQUEST?:** Feature Request

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Feature Request:**
Y

**Describe the feature:**

Currently to figure out which envoy version is being used, one would need to trace back by using the docker SHA specified in the pilot repo to the git SHA in the proxy repo, to get the git SHA of the envoy repo.
Even in the docker container version command returns `/usr/local/bin/envoy  version: 0//DEBUG`

Would it be possible to expose this more explicitly as part of the docker or part of the github repo itself?

**Comment by andraxylia** [comment]
Issue moved to [istio/istio #6572](https://github.com/istio/istio/issues/6572) via [**ZenHub**](https://www.zenhub.com/)
