### ISSUE TITLE
Show precedence when using `istioctl get XYZ`

### ISSUE THREAD

**Issue by saturnism** [istio/old_issues_repo#233]
**Is this a BUG or FEATURE REQUEST?:** FEATURE REQUEST

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Y

**Bug:** N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
$ istioctl version
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Installed istio.yaml

**What happened**: `istioctl get routerules` displays the route rules, but no information on precedence.

**What you expected to happen:** Show precedence information in the route rule too, potentially sort by precedence.

**How to reproduce it:**
Run `istioctl get routerules`

**Feature Request:** Y

**Describe the feature:**
Show precedence information in the route rule too, potentially sort by precedence too.

**Comment by kyessenov** [comment]
Precedence has been deprecated AFAIK, so this is not going to be
implemented.

**Comment by oaktowner** [comment]
If there is no precedence, how does a user decipher how a specific call will be routed?

**Comment by louiscryan** [comment]
The new networking APIs define all the routes in order for a specific host in a single resource. This gives clear precedence.

**Comment by louiscryan** [comment]
See https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService
