### ISSUE TITLE
Does Istio have a plan to support service name in HTTP URL path or header?

### ISSUE THREAD

**Issue by zhaohuabing** [istio/old_issues_repo#243]
**Feature Request:**
Y

**Describe the feature:**
As I understand it, currently Istio take the "host" part of the http request as the service name and use it to find the destination service. For example, in the Bookinfo example, the service name "details" is extracted from the host part of request "http://details:9080/...". 

While I understand this is a logical approach for Istio because of its tight relationship with kubernetes, there're also other ways to locate the service name in Microservice practices. Service name may also be part of URL path or even an HTTP header. For example, a request may be sent to a URL like http://IP:Port/api/details/v1/{resource_id}, in which the service name "details" should be extracted from URL path.

Will Istio plan to support service name in HTTP URL path or header? Or maybe it's already supported somewhere I don't noticed?

Thanks,
Huabing

**Comment by ldemailly** [comment]
how is you application getting IP:Port in the example above, and why can't it use a name ?

Istio is using a header already it's the Host: header, which you can set if needed (you could set that header even if you use the IP above)?

This being said, yes, in the most general term, being able to change/adapt the routes flexibly makes sense; as well as supporting some sort of ip/port -> service reverse lookup that works in all environments; but that's probably not changing before-1.0

We have been talking for instance about mixer rules and adapter being able to influence routing, set headers etc... but that's not there yet

@costinm does v1alpha3 covers some kind of generic flexible routing based on url fragment, headers, etc... ?
from a cursory look at https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html I don't see it but maybe ?

**Comment by louiscryan** [comment]
istio supports regex based matching on headers in an http request. that includes the standard headers host / authority & path

Take a look at https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPMatchRequest
