### ISSUE TITLE
Enhance retry/timeout functionality

### ISSUE THREAD

**Issue by jsw** [istio/old_issues_repo#251]
Feature request

**Describe the feature:**

Istio should expose at least as much config as envoy proxy supports. One apparently missing feature is configuring the `retry-on` policy https://www.envoyproxy.io/docs/envoy/v1.6.0/configuration/http_filters/router_filter.html#config-http-filters-router-x-envoy-retry-on

Additional parameters that would be useful
* connect timeout
* socket/read/idle timeout (maximum time to wait between packets)

**Comment by sakshigoel12** [comment]
@costinm can you update this issue

**Comment by costinm** [comment]
We can try to get it for 1.0 - 0.8 has too much churn.

**Comment by louiscryan** [comment]
Duplicate of #235
