### ISSUE TITLE
"Using Istio Routing Rules with Ingress" does not work as expected

### ISSUE THREAD

**Issue by fleeto** [istio/old_issues_repo#282]
**Is this a BUG or FEATURE REQUEST?:**

Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.7.1
kubectl version: 1.10
api-server version: 1.8
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.

No

**What happened**:

curl -s http://www.microservice.xyz/delay/10  0.01s user 0.01s system 0% cpu 12.209 total

**What you expected to happen:**

It should return after 4 seconds.

**How to reproduce it:**

Follow the document:

https://istio.io/docs/tasks/traffic-management/ingress.html

1. apply isto-injected httpbin.
2. apply the ingress resource.
3. apply the routerule.
4. curl..

**Feature Request:**
N

**Describe the feature:**

**Comment by ayj** [comment]
Can you provide the failing curl command with full output/errors?

**Comment by fleeto** [comment]
The routerule:

~~~yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: status-route
spec:
  destination:
    name: httpbin
  match:
    # Optionally limit this rule to istio ingress pods only
    source:
      name: istio-ingress
      labels:
        istio: ingress
    request:
      headers:
        uri:
          prefix: /delay/ #must match the path specified in ingress spec
              # if using prefix paths (/delay/.*), omit the .*.
              # if using exact match, use exact: /status
  route:
  - weight: 100
  httpReqTimeout:
    simpleTimeout:
      timeout: 4s
~~~

The command
~~~sh
curl -v http://www.microservice.xyz/delay/7                                                  [4:44:25]
*   Trying 52.163.113.44...
* TCP_NODELAY set
* Connected to www.microservice.xyz (52.163.113.44) port 80 (#0)
> GET /delay/7 HTTP/1.1
> Host: www.microservice.xyz
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< server: envoy
< date: Thu, 12 Apr 2018 20:45:48 GMT
< content-type: application/json
< access-control-allow-origin: *
< access-control-allow-credentials: true
< content-length: 480
< x-envoy-upstream-service-time: 7018
<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "www.microservice.xyz",
    "User-Agent": "curl/7.54.0",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "94069a9e8c8ba13e",
    "X-B3-Traceid": "94069a9e8c8ba13e",
    "X-Envoy-Internal": "true",
    "X-Request-Id": "cfcc399c-680e-9041-ba56-2df1275ed942"
  },
  "origin": "10.240.0.4",
  "url": "http://www.microservice.xyz/delay/7"
}
* Connection #0 to host www.microservice.xyz left intact
~~~

Because the delay of 7 seconds is greater  than 4, so It should return a status code of 503, not 200

**Comment by andraxylia** [comment]
Could you please try 0.8 and Gateway?
https://istio.io/blog/2018/v1alpha3-routing/

Ingress + RR is deprecated.
