### ISSUE TITLE
Specify httpFault and tcpFault delay as distribution

### ISSUE THREAD

**Issue by spockz** [istio/old_issues_repo#298]
**Feature Request:**
Y

**Describe the feature:**
Currently, it is possible to configure the delay as a [fixed or exponential](https://istio.io/docs/reference/config/istio.routing.v1alpha1.html#HTTPFaultInjection.Delay) delay. Many of our performance metrics from production are captured in min, max, avg, and several percentile (p95,p99,p999,etc.) values. It would be useful for us to be able to configure faults to mimick production in our test environment.

**Comment by andraxylia** [comment]
Issue moved to [istio/istio #6567](https://github.com/istio/istio/issues/6567) via [**ZenHub**](https://www.zenhub.com/)
