### ISSUE TITLE
istio-proxy debug image doesn't have curl

### ISSUE THREAD

**Issue by mchendil82** [istio/old_issues_repo#300]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y/N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version - 0.7.1
kubectl version - 1.10.1
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
Yes - I have installed latest Istio 0.7.1 version with kubernetes 1.10.1

**What happened**:

After enabling Istio-Auth, I am trying to validate HTTPS connection between envoy containers as instructed by the following URL: https://istio.io/docs/tasks/security/mutual-tls.html#testing-the-authentication-setup and tried to test HTTPS connection between envoy containers, especially with debug option to enable curl in the istio-proxy but it failed to enable curl in the istio-proxy containers or in other words istio-proxy debug image doesn't have curl package installed..

Deployment details with debug image:

svc2
app: svc2
version: v1
1 / 1
4 days
xxxxxxx.io/istio-svc2:2.0
**docker.io/istio/proxy_debug:0.7.1**
docker.io/istio/proxy_init:0.7.1
alpine 

**What you expected to happen:**
I should able to enable curl and check https connection bettween Istio-proxies with CURL call using debug istio-proxy image

**How to reproduce it:**
Follow the  URL and to check mTLS : https://istio.io/docs/tasks/security/mutual-tls.html#testing-the-authentication-setup 

**Feature Request:**
N

**Describe the feature:**

**Comment by ejether** [comment]
+1 I've also seen this.

**Comment by ejether** [comment]
Actually, it looks like a pod restart was required after re-configuring with `--debug`. The image in the new pod does have `curl`.

**Comment by andraxylia** [comment]
fixed.
