### ISSUE TITLE
Istio Ingress TLS key management use ACM

### ISSUE THREAD

**Issue by truyet** [istio/old_issues_repo#305]
**Is this a BUG or FEATURE REQUEST?:**
FEATURE REQUEST
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version  0.7.1
kubectl version 1.10.1
```

**Is Istio Auth enabled or not ?**
Not

**What happened**:
I deploy kubernetes cluster to aws use kops. Istio deployed on this cluster. Now I config Istio Ingress allow HTTPS use TLS Key on Amazon Certificate Manager (ACM) following:
https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws

But Ingress service throw error file not found: /etc/istio/ingress-certs or /etc/certs
 
**What you expected to happen:**
We can apply [ssl-support-on-aws](https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws) to istio ingress service.

**Feature Request:**
Y

**Describe the feature:**
Istio Ingress service support Amazon Certificate Management

Reference:
https://medium.com/kokster/how-to-setup-nginx-ingress-controller-on-aws-clusters-7bd244278509
https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/tls-termination

**Comment by andraxylia** [comment]
Issue moved to [istio/istio #6566](https://github.com/istio/istio/issues/6566) via [**ZenHub**](https://www.zenhub.com/)
