### ISSUE TITLE
Recovered pilot causes CrashLoopBackOff in cluster, killing/recreating all Pilot pods fixes it.

### ISSUE THREAD

**Issue by KresoDenis** [istio/old_issues_repo#311]
**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y/N
Y
**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.7.1
kubectl version 1.9.6 
```

**Is Istio Auth enabled or not ?**
Auth disabled

**What happened**:
I have 3 istio pilots on 3 nodes. If one nodes after few days dies and returns. Out of sudden i start getting a lot of CrashLoopBackOff on my applications all over cluster where istio-proxy is injected.

After i kill and recreate all PILOT pods things start to return back to normal with time. To quick things up i kill and recreate CrashLoopBackOff pods but it gets to normal without me killing those pods.

My refresh configs are
rdsRefreshDelay: 30s
discoveryRefreshDelay: 30s

I tried 
curl http://istio-pilot:15003/v1/registration

from ingress to see responses, and they are incossistend. But they only differ in AZ tags missing. There is ticket for AZ tags but its not relevant to my case according to those.

After i kill all PILOT pods and test registration curl things are consistent and everything goes back to normal.

Not much in isto-proxy logs. Mainly just AZ warnings.

**What you expected to happen:**
Recovered pilot not bringing istio-proxyies all over cluster down.

**How to reproduce it:**
Have node go down, and return back after some time with one pilot on it.

**Feature Request:**
Y/N

**Describe the feature:**

**Comment by KresoDenis** [comment]
there are theese in the pilot logs 
``
Failed to update lock: Operation cannot be fulfilled on configmaps "istio-ingress-controller-leader-istio": the object has been modified; please apply your changes to the latest version and try again
``

**Comment by kyessenov** [comment]
The log item is coming from the ingress status syncer and is mostly
harmless.

**Comment by KresoDenis** [comment]
What can happened to 3 replicas of pilots that one of them starts returning different json and make some istio-proxy fails. Once i kill them again they start returning same json, and proxyies recover to normal.

It happened again but this time without node failing. It just takes some time or changes in number of pods with istio proxies. Not sure why this happens.

**Comment by mandarjog** [comment]
We are investigating a similar problem, that was reported under node restart conditions.
Details to follow.

**Comment by mandarjog** [comment]
ref https://github.com/istio/istio/issues/5391

**Comment by andraxylia** [comment]
Issue moved to [istio/istio #6565](https://github.com/istio/istio/issues/6565) via [**ZenHub**](https://www.zenhub.com/)
