### ISSUE TITLE
gRPC Streaming - is it supported or not?

### ISSUE THREAD

**Issue by reuvenharrison** [istio/old_issues_repo#322]
**Is this a BUG or FEATURE REQUEST?:** FEATURE REQUEST

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: yes

**Bug:**
N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.7.1
kubectl version 1.8.6
kubernetes version 1.8.8-gke.0
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
stable istio_auth.yaml.

**What happened**:
I am using gRPC streaming from a service outside the cluster, through ingress and to an service in the cluster.
After ~15 minutes of an idle connection, the server-side stopped being able to stream to the client (the server would send a message but the client wouldn't receive it).
Neither the client nor the server generated any errors.
I added an applicative keep-alive (server sends hello to client once a minute) and now the stream seems to be stable.
I suspect that one of the envoys on the path (ingress of the service sidecar) was terminating the connection.

**What you expected to happen:**
I expected to receive an error when the connection is broken.

**How to reproduce it:**
Go code is quite complex but I would be glad to help create the automated test.

**Feature Request:**
Y

**Describe the feature:**
Add testing and documentation for gRPC streaming in Istio.

**Comment by louiscryan** [comment]
Sounds like a default timeout issue either in Envoy or in the grpc library. 

Which grpc client are you using?

**Comment by reuvenharrison** [comment]
google.golang.org/grpc

**Comment by lizan** [comment]
Yeah I believe it is a default timeout in Envoy, we added an option to extend gRPC timeout:
https://github.com/envoyproxy/envoy/pull/3564

Does your client or server see any error code generated by Envoy?

**Comment by louiscryan** [comment]
Strong possibility it will be fixed by

@rshriram 

https://github.com/istio/istio/pull/6081
