### ISSUE TITLE
Application is not available at all (404s returned all the time) - envoy never knows about application

### ISSUE THREAD

**Issue by dpacierpnik** [istio/old_issues_repo#329]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: YES

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
Istio version: 0.7.1
Kubernetes version: 1.9.0

**Is Istio Auth enabled or not ?**
NOT (istio.yaml used)

**What happened**:
After few runs, Istio starts to be unstable. Application is not available at all (Ingress Controller returns 404s all the time). It looks like Ingress Controller (Envoy) never knows about application.

More detailed logs can be found here: https://github.com/dpacierpnik/istio-0.7-issues/tree/master/issue_logs/03_istio_no_auth_many_resources

**What you expected to happen:**
I expect the Pilot works stable and my apps are available all the time ;)

**How to reproduce it:**
To reproduce, you can use the following application https://github.com/dpacierpnik/istio-0.7-issues Just follow the README

**Comment by piotrmiskiewicz** [comment]
I’ve also observed HTTP 404 problem.
I was trying to run the described scenario. Restart istio-pilot helps. After the restart I see test succeeded.  
Additionally, I’ve created two pods – client and target (pod and service). Client was calling the target periodically. Client could not do the call – got HTTP 404. When I set the http Transport DisableKeepAlive flag to false – the client can do the call.

**Comment by louiscryan** [comment]
Can you retest with the 0.8 release. There were many stability improvements in the configuration pipeline for Envoy that may have resolved your issue.

Thanks!

**Comment by dpacierpnik** [comment]
It works now. You can close this ticket.

Thanks,
Damian

**Comment by louiscryan** [comment]
Thanks.
