### ISSUE TITLE
lds: fetch failure: network error

### ISSUE THREAD

**Issue by awalmsley** [istio/old_issues_repo#355]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
istio-auth.yaml

**What happened**:
Installed the book info application and attempted to retrieve the product page, received a 503 response code

The product page istio-proxy log contains the following error
```
productpage-v1-5f9b797dfc-74pzq istio-proxy [2018-05-24 21:23:55.275][10][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
```
**What you expected to happen:**
The product page should be returned

**How to reproduce it:**
curl http://$GATEWAY_URL/productpage

**Feature Request:**
Y/N

**Describe the feature:**

**Comment by SachinHg** [comment]
Hi @awalmsley, any updates on this issue? I am hitting exactly the same issue.

**Comment by filipre** [comment]
upgrading Istio to 0.8 solved the issue for us.

**Comment by awalmsley** [comment]
Haven't seen the error since upgrading to Istio 0.8, closing the issue.
